"""
This type stub file was generated by pyright.
"""

CREATE_NEW_PROCESS_GROUP = ...
DETACHED_PROCESS = ...
REGISTERED = ...
def start_detached(executable, *args): # -> Any:
    """
    Starts a fully independent subprocess (with no parent)
    :param executable: executable
    :param args: arguments to the executable, eg: ['--param1_key=param1_val', '-vvv' ...]
    :return: pid of the grandchild process
    """
    ...

