"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.chromium.options import ChromiumOptions as _ChromiumOptions

class ChromeOptions(_ChromiumOptions):
    _session = ...
    _user_data_dir = ...
    @property
    def user_data_dir(self): # -> str | None:
        ...
    
    @user_data_dir.setter
    def user_data_dir(self, path: str): # -> None:
        """
        Sets the browser profile folder to use, or creates a new profile
        at given <path>.

        Parameters
        ----------
        path: str
            the path to a chrome profile folder
            if it does not exist, a new profile will be created at given location
        """
        ...
    
    def handle_prefs(self, user_data_dir): # -> None:
        ...
    
    @classmethod
    def from_options(cls, options): # -> Self:
        ...
    


