"""
This type stub file was generated by pyright.
"""

import threading

logger = ...
class Reactor(threading.Thread):
    def __init__(self, driver: Chrome) -> None:
        ...
    
    def add_event_handler(self, method_name, callback: callable): # -> None:
        """

        Parameters
        ----------
        event_name: str
            example "Network.responseReceived"

        callback: callable
            callable which accepts 1 parameter: the message object dictionary

        Returns
        -------

        """
        ...
    
    @property
    def running(self): # -> bool:
        ...
    
    def run(self): # -> None:
        ...
    
    async def listen(self): # -> None:
        ...
    


