"""
This type stub file was generated by pyright.
"""

import selenium.webdriver.remote.webelement
from typing import List

class WebElement(selenium.webdriver.remote.webelement.WebElement):
    def click_safe(self): # -> None:
        ...
    
    def children(self, tag=..., recursive=...) -> List[selenium.webdriver.remote.webelement.WebElement]:
        """
        returns direct child elements of current element
        :param tag: str,  if supplied, returns <tag> nodes only
        """
        ...
    


class UCWebElement(WebElement):
    """
    Custom WebElement class which makes it easier to view elements when
    working in an interactive environment.

    standard webelement repr:
    <selenium.webdriver.remote.webelement.WebElement (session="85ff0f671512fa535630e71ee951b1f2", element="6357cb55-92c3-4c0f-9416-b174f9c1b8c4")>

    using this WebElement class:
    <WebElement(<a class="mobile-show-inline-block mc-update-infos init-ok" href="#" id="main-cat-switcher-mobile">)>

    """
    def __init__(self, parent, id_) -> None:
        ...
    
    @property
    def attrs(self):
        ...
    
    def __repr__(self): # -> str:
        ...
    


