"""
This type stub file was generated by pyright.
"""

log = ...
class CDPObject(dict):
    def __init__(self, *a, **k) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class PageElement(CDPObject):
    ...


class CDP:
    log = ...
    endpoints = ...
    def __init__(self, options: ChromeOptions) -> None:
        ...
    
    def tab_activate(self, id=...): # -> Data | Response | None:
        ...
    
    def tab_list(self): # -> list[PageElement]:
        ...
    
    def tab_new(self, url): # -> Data | Response | None:
        ...
    
    def tab_close_last_opened(self): # -> Data | Response | None:
        ...
    
    async def send(self, method: str, params: dict): # -> None:
        ...
    
    def get(self, uri): # -> Any | None:
        ...
    
    def post(self, uri, data: dict = ...): # -> Data | Response | None:
        ...
    
    @property
    def last_json(self): # -> Any | None:
        ...
    


