"""
This type stub file was generated by pyright.
"""

import platform

logger = ...
IS_POSIX = ...
class Patcher:
    lock = ...
    exe_name = ...
    platform = ...
    if platform.endswith("win32"):
        d = ...
    else:
        d = ...
    data_path = ...
    def __init__(self, executable_path=..., force=..., version_main: int = ..., user_multi_procs=...) -> None:
        """
        Args:
            executable_path: None = automatic
                             a full file path to the chromedriver executable
            force: False
                    terminate processes which are holding lock
            version_main: 0 = auto
                specify main chrome version (rounded, ex: 82)
        """
        ...
    
    def auto(self, executable_path=..., force=..., version_main=..., _=...): # -> bool | None:
        """

        Args:
            executable_path:
            force:
            version_main:

        Returns:

        """
        ...
    
    def driver_binary_in_use(self, path: str = ...) -> bool:
        """
        naive test to check if a found chromedriver binary is
        currently in use

        Args:
            path: a string or PathLike object to the binary to check.
                  if not specified, we check use this object's executable_path
        """
        ...
    
    def cleanup_unused_files(self): # -> None:
        ...
    
    def patch(self): # -> bool:
        ...
    
    def fetch_release_number(self): # -> LooseVersion:
        """
        Gets the latest major version available, or the latest major version of self.target_version if set explicitly.
        :return: version string
        :rtype: LooseVersion
        """
        ...
    
    def parse_exe_version(self): # -> LooseVersion | None:
        ...
    
    def fetch_package(self): # -> str:
        """
        Downloads ChromeDriver from source

        :return: path to downloaded file
        """
        ...
    
    def unzip_package(self, fp): # -> str:
        """
        Does what it says

        :return: path to unpacked executable
        """
        ...
    
    @staticmethod
    def force_kill_instances(exe_name): # -> bool:
        """
        kills running instances.
        :param: executable name to kill, may be a path as well

        :return: True on success else False
        """
        ...
    
    @staticmethod
    def gen_random_cdc(): # -> bytes:
        ...
    
    def is_binary_patched(self, executable_path=...): # -> bool:
        ...
    
    def patch_exe(self): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __del__(self): # -> None:
        ...
    


